@startuml Voting process
start
:opt-in for voting;
:voting right acquisition;
if (has right to vote?) then (yes)
    :show right to vote;
    :put preference into ballot;
    :vote registration;
else (no)
    :refuse vote
    __must__ opt-in for voting;
endif
:wait until votation end;
:ballot;
:results pubblication;
stop
@enduml