@startuml Open Ballot
title Open Ballot with Algornad - sequence diagram
autonumber

participant "Voter Account" as VA
participant "Stakeholder Account" as SA
participant "Algorand Node" as N
participant "Stateful Smart Contract"  as  ASC
participant "Algorand Blockchain" as B


== Initialization ==
SA -> N : Voting asset configuration
N -> B : create asset
B --> N : <OK,assetID>
N --> SA : <OK,assetID>
SA -> N : Stateful contract configuration
N -> B : create contract
B --> N :<OK,appID>
N --> SA :<OK,appID>

== Registration period ==
VA -> N : Opt-in for voting asset
N --> B : account X opted in for assetID
VA -> N : Opt-in for voting contract
N --> ASC : account X opted in for appID
alt is registration round
    ASC --> N : ok
else transaction fails
    ASC --> N : Transaction refused
end
...within registration round...
SA -> VA : send 1 Voting Asset
== Voting period ==
group Atomic Transfer
VA -> N : create transfer to SA
N --> SA : send 1 Voting Asset from VA to SA
VA -> N : **application call** to appID with ""-args //voting preference//""
N --> ASC : **application call** with ""-args //voting preference//""
end
ASC --> ASC : Evaluate transactions in atomic transfer
alt Voter has spent asset AND has opted into app AND is voting round
    ASC --> B : update local and global state
else transactions fail
    ASC --> VA : Transactions refused
end
== End period ==

@enduml